/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PatchPatchIdImport } from './routes/patch.$patchId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PatchPatchIdRoute = PatchPatchIdImport.update({
  id: '/patch/$patchId',
  path: '/patch/$patchId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/patch/$patchId': {
      id: '/patch/$patchId'
      path: '/patch/$patchId'
      fullPath: '/patch/$patchId'
      preLoaderRoute: typeof PatchPatchIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patch/$patchId': typeof PatchPatchIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patch/$patchId': typeof PatchPatchIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/patch/$patchId': typeof PatchPatchIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patch/$patchId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patch/$patchId'
  id: '__root__' | '/' | '/patch/$patchId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatchPatchIdRoute: typeof PatchPatchIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatchPatchIdRoute: PatchPatchIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/patch/$patchId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/patch/$patchId": {
      "filePath": "patch.$patchId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
